In [1]:
import numpy as np

In [2]:
def factor_calc(num1):
    return np.math.factorial(num1)

In [3]:
def count_match(num1, num2):
    numerator = factor_calc(num2)
    denominator = factor_calc((num2 - num1)) * factor_calc(num1)
    return numerator / denominator

Задача №1

In [39]:
np.random.binomial(n=85, p=0.8, size=100)

array([72, 71, 68, 65, 62, 62, 82, 66, 71, 64, 70, 62, 66, 71, 72, 65, 68,
       63, 65, 73, 71, 75, 69, 64, 70, 62, 75, 66, 70, 63, 64, 71, 71, 68,
       68, 64, 67, 68, 75, 66, 74, 71, 75, 71, 71, 61, 68, 70, 71, 74, 73,
       67, 74, 71, 67, 68, 63, 71, 70, 67, 68, 69, 64, 69, 67, 70, 73, 65,
       66, 78, 70, 75, 67, 63, 71, 74, 69, 69, 66, 59, 74, 66, 72, 69, 70,
       68, 69, 62, 65, 66, 75, 71, 74, 72, 66, 74, 73, 62, 66, 68])

In [50]:
count_match(85, 100)*(np.math.pow(0.8, 85)*(np.math.pow(0.2, 15)))

0.04806179370074656

Задача №2

In [43]:
np.random.binomial(n=0, p=0.0004, size=5000)

array([0, 0, 0, ..., 0, 0, 0])

In [51]:
count_match(0, 5000)*(np.math.pow(0.0004, 0)*(np.math.pow(1-0.0004, 5000)))

0.13528114551440706

In [52]:
np.random.binomial(n=2, p=0.0004, size=5000)

array([0, 0, 0, ..., 0, 0, 0])

In [53]:
count_match(2, 5000)*(np.math.pow(0.0004, 2)*(np.math.pow(1-0.0004, 5000)))

0.2705081785706084

Задача №3

In [56]:
np.random.binomial(n=70, p=0.5, size=144)

array([40, 36, 35, 31, 37, 41, 38, 32, 37, 40, 31, 34, 33, 39, 39, 41, 35,
       35, 30, 32, 42, 35, 33, 32, 36, 26, 36, 42, 36, 34, 33, 35, 38, 27,
       39, 38, 33, 30, 31, 38, 32, 39, 34, 33, 25, 33, 30, 37, 36, 34, 36,
       28, 39, 39, 29, 44, 31, 34, 46, 39, 39, 42, 31, 36, 40, 30, 40, 30,
       38, 42, 31, 36, 35, 40, 41, 38, 34, 33, 38, 34, 33, 33, 34, 30, 30,
       33, 38, 43, 33, 20, 33, 40, 36, 32, 37, 33, 38, 37, 37, 32, 39, 32,
       37, 39, 32, 32, 36, 39, 29, 33, 30, 32, 36, 43, 33, 37, 41, 37, 35,
       44, 35, 40, 38, 43, 43, 37, 33, 34, 27, 35, 32, 38, 35, 33, 35, 31,
       34, 43, 35, 41, 38, 35, 36, 34])

In [59]:
count_match(70, 144)*(np.math.pow(0.5, 70)*(np.math.pow(1-0.5, 144-70)))

0.06281178035144776

Задача №4

In [60]:
def bayes_method(num1, num2):
    return num1 * num2

In [71]:
1-bayes_method(1/15, 1/55)

0.9987878787878788